name: Docker Multi-architecture Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        run: |
            docker build --tag ${{env.USER}}/fskintra:${{matrix.arch}}  .
            docker push ${{env.USER}}/fskintra:${{matrix.arch}}
    
    
  docker_manifest:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create and push manifest
        run: |
            docker manifest create ${{env.USER}}/fskintra ${{env.USER}}/fskintra:amd64 ${{env.USER}}/fskintra:arm64
            docker manifest push ${{env.USER}}/fskintra

    


